name: envds-book
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - ghp-import
  - hvplot
  - intake
  - intake-xarray
  - bottleneck
  - pooch
  - pytorch==1.9.0
  - torchvision==0.10.0
  - tensorflow==2.2.0
  - geoviews
  - iris==3.0.1
  - urllib3
  - opencv
  - rasterio
  - pip
  - pip:
      - scikit-image
      - aiohttp
      - albumentations