name: forest-modelling-treecrown_detectreeRGB
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - intake
  - intake-xarray
  - rasterio
  - opencv
  - pytorch==1.8.0
  - torchvision==0.9.0
  - tqdm
  - hvplot
  - cartopy
  - datashader
  - jinja2==3.0.2
  - pip
  - pip:
      - pycurl
      - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git